# This is to validate the behavior of OIDC federation using "aws-actions/configure-aws-credentials"
# Refer to the following documents for more details
# - https://github.com/aws-actions/configure-aws-credentials
# - https://docs.github.com/en/actions/how-tos/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services

name: Validate AWS OIDC Federation

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

jobs:
  FederationTest:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-1
          role-to-assume: arn:aws:iam::096966628981:role/oicd-role-assume-test-Role-sPVH97lvfGzD
          role-session-name: testrolesession
        
      - name: List S3 buckets
        run: aws s3 ls
